Migrate to null safety
kmorkos/dart_random_choice pull request #2
Opened 2021-01-26 19:02 UTC by TimWhiting

Hi,

There were no changes needed to support dart's nullsafety other than updating dependencies and the sdk version.

Thanks for the package.

2021-02-09 04:01 UTC, kmorkos commented
Thank you for this! I will try to push this in the next few days.

2021-02-15 19:45 UTC, kmorkos requested changes
Let's increment the minor version as per https://dart.dev/null-safety/migration-guide#package-version

2021-02-15 19:45 UTC, kmorkos commented on pubspec.yaml
> +version: 0.0.3-nullsafety.0
Following https://dart.dev/null-safety/migration-guide#package-version, I'd prefer to increment the minor version

```suggestion
version: 0.1.0-nullsafety.0
```

2021-02-15 19:45 UTC, kmorkos commented on pubspec.yaml
> +  test: ^1.16.0-nullsafety.16
```suggestion
  test: ^1.16.2
```

2021-02-15 19:45 UTC, kmorkos commented on CHANGELOG.md
> +## [0.0.3-nullsafety.0] - 01/26/2021
```suggestion
## [0.1.0-nullsafety.0] - 02/15/2021
```

2021-02-15 20:36 UTC, TimWhiting commented
Should be good to go now.

2021-02-15 21:14 UTC, kmorkos approved these changes

2021-02-15 21:16 UTC, merged

2021-02-15 21:19 UTC, kmorkos commented
Published https://pub.dev/packages/dart_random_choice/versions/0.1.0-nullsafety.0. Thank you for your contribution @TimWhiting!